# Production environment values for README to Word Converter

# Production scaling
replicaCount: 3

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# Enable autoscaling for production load
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

# Larger storage for production
persistence:
  size: 20Gi
  storageClass: "fast-ssd"  # Use SSD storage class if available

# Production ingress with proper domain
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: readme2word.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: readme2word-tls
      hosts:
        - readme2word.yourdomain.com

# Enable security features
networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8501
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 443  # HTTPS for Mermaid API
        - protocol: TCP
          port: 53   # DNS
        - protocol: UDP
          port: 53   # DNS

# Production health checks
healthcheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /_stcore/health
      port: http
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /_stcore/health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Production affinity rules
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - readme2word
        topologyKey: kubernetes.io/hostname

# Disable debug mode
debug:
  enabled: false
  logLevel: "INFO"

# Production environment variables
env:
  - name: PYTHONPATH
    value: "/app"
  - name: PYTHONDONTWRITEBYTECODE
    value: "1"
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
    value: "true" 